# Generated by Django 6.0.4 on 2026-04-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_food_options_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='Weight',
            field=models.CharField(default=10, max_length=100, verbose_name='Weight'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='Description',
            field=models.TextField(max_length=200, verbose_name='Description'),
        ),
    ]
